# SPDX-FileCopyrightText: 2024 Yun Hsiao Wu <yunhsiaow@gmail.com>
# SPDX-License-Identifier: MIT

version = 1

[[annotations]]
path = [
    "Extensibility.uplugin",
    "SourcePatch/**/*.patch",
]
SPDX-FileCopyrightText = "2024 Yun Hsiao Wu <yunhsiaow@gmail.com>"
SPDX-License-Identifier = "MIT"
